### DISCUSSION TITLE
Openning certain youtube playlist on bravia tv

### DISCUSSION THREAD

**Discussion by stefancvetkovic** [custom-components/media_player.braviatv_psk#74] [Q&A]
I have this action for my sony bravia to play youtube, but how can I pass through playlist for certain playslist on youtube?
```
type: service
id: braviatv_psk.bravia_open_app
data:
  entity_id: media_player.bedroom_bravia
  uri: >-
    com.sony.dtv.com.google.android.youtube.tv.com.google.android.apps.youtube.tv.activity.ShellActivity
```
