### ISSUE TITLE
Scene in the attributes

### ISSUE THREAD

**Issue by hekm77** [custom-components/media_player.braviatv_psk#14]
Hi @gerard33 
Is it possible to add the selected scene on TV to the attributes?

_command_
```
curl -v -H "Content-Type:application/json" -H "X-Auth-PSK: sony" -d '{"method":"getSceneSetting","id":2,"params":[],"version":"1.0"}' http://192.168.1.19/sony/videoScreen
```

_response_
```
{  
   "id":2,
   "result":[  
      {  
         "candidate":[  
            {  
               "value":"general"
            },
            {  
               "value":"auto"
            },
            {  
               "value":"auto24pSync"
            },
            {  
               "value":"photo"
            },
            {  
               "value":"music"
            },
            {  
               "value":"cinema"
            },
            {  
               "value":"game"
            },
            {  
               "value":"graphics"
            },
            {  
               "value":"sports"
            },
            {  
               "value":"animation"
            }
         ],
         "currentValue":"general"
      }
   ]
}
```

**Comment by gerard33** [comment]
Based on your info it should be possible.
Curious though what use case you have for it?

**Comment by hekm77** [comment]
I would like to set a certain scene depending on the enabled source.
My devices are connected like this:

```
 desktop       --> hdmi1
                        \
                         sony soundbar --> sony tv hdmi(arc)
                        /   
 media player  --> hdmi2
```
That's about right:
```
automation:
  - alias: sony_bravia_tv
    initial_state: true
    trigger:
      - platform: state
        entity_id: media_player.sony_bravia_tv
        to: 'on'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: media_player.dunehd
            state: 'on'
          - condition: template
            value_template: "{{ state_attr('media_player.sony_bravia_tv', 'scene') != 'movie' }}"
    action:
      - service: shell_command.sonytv_scene_movie


 shell_command:
   sonytv_scene_movie: |-
     curl -v -H "Content-Type:application/json" -H "X-Auth-PSK: sony" -d '{"method":"setSceneSetting","id":2,"params":[{"value":"movie"}],"version":"1.0"}' http://192.168.1.19/sony/videoScreen
```
