### ISSUE TITLE
Error when power tv on

### ISSUE THREAD

**Issue by alonalon** [custom-components/media_player.braviatv_psk#21]
When I try to power my tv on I got following error message

```
Invalid response: {'error': [7, 'not power-on'], 'id': 1}
  request path: sony/avContent
  request params: {"method": "setPlayContent", "params": [{"uri": "extInput:hdmi?port=2"}], "id": 1, "version": "1.0"}
```

And in frontend when trigger power on it just says `TV started, waiting for program`

Ohterwise everything works as expected when the tv is on.
Any idéas why this error message occurs?

My config looks like this

```
media_player:
  - platform: braviatv_psk
    host: !secret bravia_tv
    mac: !secret bravia_mac
    psk: !secret bravia_psk
```
