### ISSUE TITLE
Inputs Not Loading

### ISSUE THREAD

**Issue by mbaran5** [custom-components/media_player.braviatv_psk#24]
I cannot seem to determine the exact reproduction steps, but 99/100 times I restart HA I will lose my input states. 

Currently my device shows no inputs. 

![image](https://user-images.githubusercontent.com/583865/75199579-57144800-5718-11ea-9cad-a2d8e77f8c8e.png)

Here's my configuration.yaml section

```
media_player:
  - platform: braviatv_psk
    host: 1.1.1.1
    psk: ######
    mac: xx:xx:xx:xx:xx:xx
    amp: True
    android: True
    sourcefilter:
      - ' HD'
      - HDMI
    name: LivingRoomTV
```

On the occasional usage, I will get the inputs actually saved within states. TV is XBR-85GX850 w/ Android.
