### ISSUE TITLE
Unable to See Other Buttons

### ISSUE THREAD

**Issue by celeritas0725** [custom-components/media_player.braviatv_psk#26]
braviatv_psk is working as expected but I just do not know how the other buttons will appear (ex. numbers in remote, Netflix, Google Play, etc.). Can you help me out? Thank you!

media_players.yaml
```yaml
####### GF TV #######
  - platform: braviatv_psk
    name: GF TV
    host: !secret braviatv_host
    psk: !secret braviatv_psk
    mac: !secret braviatv_mac
    amp: false
    android: True
    time_format: 12H
    sourcefilter:
      - ' HD'
      - HDMI
      - 'Video'
```

![2020-04-04_000138](https://user-images.githubusercontent.com/56512303/78381218-a139f480-7607-11ea-88d1-aa7f02b2143a.png)
