### ISSUE TITLE
Cannot connect any Bravia TV

### ISSUE THREAD

**Issue by wacki4** [custom-components/media_player.braviatv_psk#30]
**Describe the issue**
I have two Bravia TV - one with Android, and one without. I cannot connect using this plugin. Android remote from sony works great.

**Expected behavior**
Devices shows on dashboard - but cannot do nothing - cannot start Android TV, starting old one works great, bo no services or buttons beside power are shown.

**Home Assistant version**
0.108.4

**Your config.yaml**
```yaml
media_player:
  - platform: braviatv_psk
    host: 192.168.0.20
    mac: fc:f1:52:f3:21:92
    psk: sony
    name: sonysypialnia
  - platform: braviatv_psk
    host: 192.168.0.21
    mac: 70:26:05:d6:fd:c2
    psk: sony
    android: True
    name: sonysalon
````

**Output of HA logs**
2020-04-16 08:21:09 WARNING (MainThread) [homeassistant.components.media_player] Updating braviatv_psk media_player took longer than the scheduled update interval 0:00:10
