### ISSUE TITLE
Failed to call service media_player/bravia_open_app. Service not found

### ISSUE THREAD

**Issue by alexandrucoman** [custom-components/media_player.braviatv_psk#35]
**Describe the issue**
Version: 3.3.4
I updated the custom component for my Home Assistant 0.110.1 installation, restarted and tried the 2 new features you describe in the HACS release : 

- OK and running great: braviatv_psk.bravia_command
- NOT WORKING: braviatv_psk.bravia_open_app

I receive the error in the subject when I try to run that service. It does not reports bad command, but the lack of the service.
I have a Sony KD-49XD7005 with the latest Android update on it. 
I have the android: True enabled
The component works perfectly with all the other functions and it's great with the HomeKit Bridge from HA.

**Expected behavior**
I cannot find the source code referring to this new service available in order to understand If i did something wrong

**Home Assistant version**
HA 0.110.1

**Screenshots**

**Some extra checks**
Please check the items below
- [ X] The correct Pre-Shared Key (PSK) is used in the configuration
- [ X] The correct static IP address of the TV is used in the configuration
- [ X] The installation instructions for the TV from [here](https://github.com/custom-components/media_player.braviatv_psk#installation-instructions-tv) are followed

**Your config.yaml**
```yaml
media_player:
  
  - platform: braviatv_psk
    host: 192.168.1.167
    psk: sony
    name: MyBraviaTV
    amp: True
    android: True
    sourcefilter:
      - ' 4K'
      - ' HD'
      - HDMI
````

**Output of HA logs**
service called: media_player.bravia_open_app
uri: com.sony.dtv.com.google.android.youtube.tv.com.google.android.apps.youtube.tv.activity.ShellActivity

Failed to call service media_player/bravia_open_app. Service not found.

Thanks
