### ISSUE TITLE
braviatv_psk.bravia_command does not honor entity_id

### ISSUE THREAD

**Issue by divanikus** [custom-components/media_player.braviatv_psk#37]
**Describe the issue**
I have two Android Bravia's (2018 & 2019 models) in my appartment. I'm trying to use `braviatv_psk.bravia_command` to send additional commands to them. But whatever entity_id I send to it, only 1 TV responds.

**Expected behavior**
2 TVs setup. Sending command_id: TvPower would toggle the exact one which is supplied within entity_id. But in reality it is always the first registered TV.

**Home Assistant version**
HA 0.110.3 (HASS.io)

**Some extra checks**
Please check the items below
- [x] The correct Pre-Shared Key (PSK) is used in the configuration
- [x] The correct static IP address of the TV is used in the configuration
- [x] The installation instructions for the TV from [here](https://github.com/custom-components/media_player.braviatv_psk#installation-instructions-tv) are followed

**Your config.yaml**
```yaml
media_player:
  - platform: braviatv_psk
    name: BR TV
    host: 192.168.0.16
    android: True
    amp: True
    psk: xxxx
  - platform: braviatv_psk
    name: YR TV
    host: 192.168.0.17
    android: True
    amp: True
    psk: xxxx
```

So sending the following:
```
command_id: TvPower
entity_id: media_player.yr_tv
```
Would actually toggle BR TV
