### ISSUE TITLE
braviatv_psk.bravia_open_app not working

### ISSUE THREAD

**Issue by adriandelcl** [custom-components/media_player.braviatv_psk#38]
**Describe the issue**
braviatv_psk.bravia_open_app not working

**Expected behavior**
Call to the service which open an app on the TV

**Home Assistant version**
0.110.3

**Some extra checks**
Please check the items below
- [x] The correct Pre-Shared Key (PSK) is used in the configuration.
- [x] The correct static IP address of the TV is used in the configuration
- [x] The installation instructions for the TV from [here](https://github.com/custom-components/media_player.braviatv_psk#installation-instructions-tv) are followed

 - Power on, channel selection, volume, etc, functions are working as expected.

![image](https://user-images.githubusercontent.com/26792759/83326205-44a72e80-a272-11ea-94f6-266fc2d79be2.png)

Youtube URI used.

**Your config.yaml**
```yaml
media_player:
  - platform: braviatv_psk
    host: 192.168.1.54
    psk: ****
    mac: 70:26:05:9F:2D:A1
    amp: True
    android: True
    name: TV Salon
    user_labels: True
  - platform: braviatv_psk
    host: 192.168.1.60
    psk: ****
    mac: AC:9B:0A:11:0D:71
    android: True
    name: TV Dormitorio
    user_labels: True
```
**Output of HA logs**
No error log generated.
