### ISSUE TITLE
braviatv_psk.bravia_command does not do anything

### ISSUE THREAD

**Issue by alienpsp** [custom-components/media_player.braviatv_psk#43]
**Describe the issue**
I installed using the HACS method and setup a card with the Mini Media Component.
I'm trying to use `braviatv_psk.bravia_command` to make a remote button in the card but the command does nothing. (I did try to fire it from the services under Dev Tools and it does nothing as well)

I manage to change source and fire command from 'braviatv_psk.bravia_open_app' with the uri I got from 
```
curl -H 'Content-Type: application/json' -H 'X-Auth-PSK:[psk]' -X POST -d "{'id': 1, 'method': 'getApplicationList', 'version': '1.0', 'params': ['']}" http://[IP]/sony/appControl
```
So the ip/psk setting are good, just the bravia_command or if i'm doing something incorrectly

**Expected behavior**
`braviatv_psk.bravia_command` to send command like a remote button but nothing happens

**Bravia custom component version**
shows v0.3.5 but the notes are showing v0.3.3/0.3.4
Note: New installation, never tried older version
```
Thanks for using this custom component.

Version 0.3.3/0.3.4 contains some really nice features:

A service is added to Home Assistant to send commands to your TV like ChannelUp, Return or Up.
This can be used to create a virtual remote or for your automations. Thanks @rchl

For Android TVs a service is added to open apps on your TV like Kodi or Youtube. 
The apps must be opened via using the uri of that app. Check the Github page of this component for examples. Thanks @rchl

It's now possible to show the HDMI labels you have set on the TV. 
This means instead of e.g. HDMI2 you can show Sky Q here. Thanks @RogerSelwyn

Home Assistant >= 0.110 is supported by renaming MediaPlayerDevice in the code to MediaPlayerEntity. 
This is backwards compatible so HA versions < 0.110 are also supported. Thanks @mories76

```

**Home Assistant version**
Home Assistant 0.117.0 on Ubuntu 22.04 LTS
Note: Never tried braviatv_psk on other version of HA
```
System Health
arch	                x86_64
dev	                false
docker	                false
hassio	                false
installation_type	Home Assistant Core
os_name	                Linux
os_version	        5.4.0-52-generic
python_version	        3.8.5
timezone	        Asia/Kuala_Lumpur
version	                0.117.0
virtualenv	        true

Lovelace
dashboards	1
mode	        storage
resources	8
views	        4
```

**Screenshots**

**Some extra checks**
Please check the items below
- [x] The correct Pre-Shared Key (PSK) is used in the configuration
- [x] The correct static IP address of the TV is used in the configuration
- [x] The installation instructions for the TV from [here](https://github.com/custom-components/media_player.braviatv_psk#installation-instructions-tv) are followed

**Your config.yaml**
```yaml
media_player:
  - platform: braviatv_psk
    host: 192.168.1.111
    psk: xxxxxx
    android: True
    sourcefilter:
      - HDMI
    time_format: 24H
````

**Card Configuration**
```yaml
type: 'custom:mini-media-player'
entity: media_player.braviavu1
name: LivingRoom
artwork: material
volume_stateless: true
volume_step: 2
max_volume: 40
background: /local/bravia.jpg
shortcuts:
  columns: 4
  buttons:
    - icon: 'mdi:netflix'                                # This works
      type: service
      id: braviatv_psk.bravia_open_app
      data:
        entity_id: media_player.braviavu1
        uri: com.netflix.ninja-com.netflix.ninja.MainActivity
    - icon: 'mdi:chart-areaspline'                        # This works
      type: service
      id: braviatv_psk.bravia_open_app
      data:
        entity_id: media_player.braviavu1
        uri: >-
          com.bloomberg.btva-com.digiflare.videa.module.core.activities.StartActivity
    - icon: 'mdi:ubuntu'                                  # This works
      type: source
      id: HDMI 2
    - icon: 'mdi:sony-playstation'                        # This works
      type: source
      id: HDMI 3 / ARC
    - icon: 'mdi:server'                                 # This doesn't works
      type: service
      id: braviatv_psk.bravia_command
      data:
        entity_id: media_player.braviavu1
        command_id: AAAAAQAAAAEAAAASAw==
    - icon: 'mdi:server'                                  # This doesn't works
      type: service
      id: braviatv_psk.bravia_command
      data:
        entity_id: media_player.braviavu1
        command_id: VolumeUp
hide:
  runtime: false
  power_state: false
  icon_state: false
  volume_level: false

```

**Output of HA logs**
No outputs for the media player entity

**Other Note**
[picture](https://imgur.com/gallery/U9axMsu) if that helps 

I also manage to get a whole list of IRCC command (that doesn't work for me as well) and I only tried the command from the list of command_id in the readme, not sure how to pull the command_id list from my TV
```
curl -H 'Content-Type: application/json' -H 'X-Auth-PSK:[psk]' -X POST -d "{'id': 1, 'method': 'getRemoteControllerInfo', 'version': '1.0', 'params': ['']}" http://[IP]/sony/system
```

**Comment by gerard33** [comment]
Do you have multiple Bravia TVs? There is a known issue that these services don't work correctly with 2 or more TVs as in that case the service will send the command to the first TV is knows, which can be other than the one you have in your config.
See also #37.

**Comment by alienpsp** [comment]
Nope, I only have 1 Bravia TV and I did check #37 when creating this post, as of now the setup was change a little to 

1 Bravia TV (same tv when posting the initial ticket)
+ 1 Sony soundbar (can navigate menu with the bravia controller which is why I want to make the controller work)

Did you happen to know other method of pulling all controller/IRCC command that I should try?

**Comment by rchl** [comment]
I have those two scripts set up that work with my TV:

```yaml
tv_assistant:
  alias: Bravia assistant
  sequence:
  - service: media_player.bravia_command
    data:
      entity_id: media_player.mybraviatv
      command_id: Assists
tv_netflix:
  alias: Netflix
  sequence:
  - data:
      command_id: Netflix
      entity_id: media_player.bravia
    service: media_player.bravia_command
```

I can't look closer at your problem right now but hopefully will find some time soon.
