### ISSUE TITLE
Some internal state make commands not work on first try

### ISSUE THREAD

**Issue by rchl** [custom-components/media_player.braviatv_psk#44]
**Describe the issue**
I don't have clear repro right now and I'm currently using this component too rarely to figure it out but when I sometimes try to turn on or off the TV (through media_player entity), the TV doesn't react on the first press, something also not on the second try. Sometimes it only starts working on the third try and then it works from thereon.

I think that would suggest that there is some internal state in the component that ignores some "commands" until the state is synchronized.

**Expected behavior**

**Bravia custom component version**
0.3.5

**Home Assistant version**
0.118.3

**Your config.yaml**
```yaml
media_player:
  - platform: braviatv_psk
    name: Bravia
    host: 192.168.2.5
    psk: sony
    amp: True
    android: True
    sourcefilter:
      - ' HD'
      - HDMI
````
