### ISSUE TITLE
Certain Commands Do Not Function in Hulu App

### ISSUE THREAD

**Issue by andrewmeepos** [custom-components/media_player.braviatv_psk#50]
**Describe the issue**
I use media_player.braviatv_psk across several Lovelace cards. Most of the time, everything works as expected. However, when the TV is open to the Hulu app, the directional commands and the confirm command do not function. This behavior seemingly only occurs while in the Hulu app.

**Expected behavior**
When the Hulu app is launched, it opens to the "Who's watching?" screen, where you are supposed to select your user profile. I have several profiles. Using my Sony remote, I can scroll up and down through the profiles, and I can click the center button between the arrows to select one of the profiles.

However, the arrow keys and the confirm commands through this custom component do not work while in the Hulu app. At first, I thought it might be an issue with my custom Lovelace cards. However, I ran services directly in Developer Tools. I tried all of the following commands. None of them function while in the Hulu app. All of these commands function in other apps or on the TV home page.
```
service: braviatv_psk.bravia_command
data:
  entity_id: media_player.sony_x900h
  command_id: Up
```
```
service: braviatv_psk.bravia_command
data:
  entity_id: media_player.sony_x900h
  command_id: CursorUp
```
```
service: braviatv_psk.bravia_command
data:
  entity_id: media_player.sony_x900h
  command_id: Down
```
```
service: braviatv_psk.bravia_command
data:
  entity_id: media_player.sony_x900h
  command_id: CursorDown
```
```
service: braviatv_psk.bravia_command
data:
  entity_id: media_player.sony_x900h
  command_id: Left
```
```
service: braviatv_psk.bravia_command
data:
  entity_id: media_player.sony_x900h
  command_id: CursorLeft
```
```
service: braviatv_psk.bravia_command
data:
  entity_id: media_player.sony_x900h
  command_id: Right
```
```
service: braviatv_psk.bravia_command
data:
  entity_id: media_player.sony_x900h
  command_id: CursorRight
```
```
service: braviatv_psk.bravia_command
data:
  entity_id: media_player.sony_x900h
  command_id: Confirm
```

**media_player.braviatv_psk version**
 v0.3.7

**Home Assistant Version**
core-2021.3.4
supervisor-2021.03.6
Raspbian GNU/Linux 10 (buster)

**configuration.yaml**
```
#Bravia PSK
media_player:
  - platform: braviatv_psk
    host: 192.168.1.17
    psk: sony
    mac: 94:DB:56:61:2B:B3
    amp: True
    android: True
    sourcefilter:
      - ' HD'
      - HDMI
    time_format: 12H
    user_labels: True
    name: Sony X900H
```
