### ISSUE TITLE
Multiple android tv's in game

### ISSUE THREAD

**Issue by stefancvetkovic** [custom-components/media_player.braviatv_psk#53]
Integration really works well for one tv, although with 2 tv's in my example, but it has serious bug I think.
When I added second tv in a separate yaml file like
```
- platform: braviatv_psk
  host: 192.168.1.49
  psk: sony
  mac: 94:db:56:xx:xx:d0
  amp: True
  android: True
  time_format: 24H
  user_labels: True
  name: livingroom_bravia
```
and In my separate file I have settings for bedroom_bravia tv:
```
- platform: braviatv_psk
  host: 192.168.1.159
  psk: sony_bedroom
  mac: 94:db:xx:xx:xx:39
  amp: True
  android: True
  time_format: 24H
  user_labels: True
  name: bedroom_bravia
```
my structure of files looks like:
https://i.imgur.com/13uwKi9.png

my config include dir looks like:
`media_player: !include_dir_merge_list media_player`

So, here is my example automation
```
- alias: Bedroom Entrance TV toggle via encoder
  id: bedroom_entrance_tv_short_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: single_short_click_3
  action:
    - service: braviatv_psk.bravia_open_app
      data:
        entity_id: media_player.bedroom_bravia
        uri: >-
          com.sony.dtv.com.ug.eon.android.tv.com.ug.eon.android.tv.TvActivity
```
so, instead of turning on bedroom tv, it constatly turns on livingroom tv
I tripple checked ip address, even I edited psk to be different, but somehow, it has still access to livingroom tv.

**Expected behavior**
I want, when I add in my media_player folder another android tv psk integration, to be able to turn on/off that exact tv, not other one.

**Bravia custom component version**
Which Bravia custom component version are you using. And did it work on a previous version, if so what was the last working version.

**Home Assistant version**
Latest (Docker/Unraid)

Configuration check is green - Success.
