### ISSUE TITLE
Media player select source will run service

### ISSUE THREAD

**Issue by skynet-network** [custom-components/media_player.braviatv_psk#76]
`**Describe` the issue**
A clear and concise description of what the issue is.

**Expected behavior**
Media player select source responds with unknown error

![Screenshot_20230208_214210_Home Assistant](https://user-images.githubusercontent.com/81412812/217650381-3c8cffda-6326-4a9e-9f23-25a09dd154bb.jpg)

Bravia custom component version 0.4.2 it the same version

**Home Assistant 2023 1 3** not sure when it worked last think it was in 2022 11

**Some extra checks**
Please check the items below
- [x ] The correct Pre-Shared Key (PSK) is used in the configuration
- [x ] The correct static IP address of the TV is used in the configuration
- [ x] The installation instructions for the TV from [here](https://github.com/custom-components/media_player.braviatv_psk#installation-instructions-tv) are followed

**Your config.yaml**
```yaml
media_player:
  - platform: braviatv_psk
    host: 192.168.1.101
    psk: sony
    mac: AA:BB:CC:DD:EE:FF
    amp: True
    android: True
    sourcefilter:
      - ' HD'
      - HDMI
    time_format: 12H
    user_labels: True
    name: MyBraviaTV
````

**Output of HA logs**
Paste the relavant output of the HA log here.

*NOTE: It might take me a while to respond on GitHub (I only maintain this in my free time), but I will respond.*
