### ISSUE TITLE
Errors when I install

### ISSUE THREAD

**Issue by rome1983** [custom-components/media_player.braviatv_psk#9]
Invalid response: {'auth_url': {'default': 'http://192.168.1.***:80/sony/webauth/auth_default', 'tv': 'http://127.0.0.1:80/sony/webauth/auth_tv'}, 'error': [403, 'Forbidden'], 'id': 1}

psk does not start with 0

```
- platform: braviatv_psk
  host: 192.168.1.239
  psk: '****'
  amp: True
  android: True
  sourcefilter:
    - ' HD'
    - HDMI
  name: X900E
```
